#gh defaults
#lsi: false
#safe: true
#source: .
#incremental: false
#highlighter: rouge
#gist:
#  noscript: false
#kramdown:
#  math_engine: mathjax
#  syntax_highlighter: rouge

#theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
twitter_username: antonpiatek
github_username:  antonpiatek

include: [".well-known"]

plugins:
 - jekyll-github-metadata
 - jekyll-mentions
 - jekyll-redirect-from
 - jekyll-sitemap
 - jemoji
 - jekyll-coffeescript
 - jekyll-default-layout
 - jekyll-gist
 - jekyll-optional-front-matter
 - jekyll-paginate
 - jekyll-readme-index
 - jekyll-titles-from-headings
 - jekyll-relative-links
 - jekyll-remote-theme
 - jekyll-feed
